stages:
  - test
  - build-deploy

unit-test-job:
  image: python:3.9-slim
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest test_app.py
    - echo "Teszt sikeresen lefutott" > test_report.txt
  artifacts:
    paths:
      - test_report.txt
    expire_in: 1 hour

docker-build-job:
  stage: build-deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
    - docker tag $DOCKER_IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
